PRAGMA foreign_keys = ON;

-- Seed catalogue public migre depuis V1.
-- Donnees exclues volontairement : users, favoris, historique, commandes, contact, forum.

DELETE FROM detail_articles_public;
DELETE FROM articles;

INSERT INTO articles (name, genres, universe, image, price, release_day) VALUES
('Lunette Gojo', 'goodies', 'jujutsu_kaisen', 'image/lunette_gojo.jpg', 57.90, NULL),
('Pendentif Jujutsu Kaisen', 'goodies', 'jujutsu_kaisen', 'image/pendentif_jujutsu_kaisen.jpg', 57.90, NULL),
('Support Gojo Geto', 'goodies', 'jujutsu_kaisen', 'image/support_gojo_geto.jpg', 27.90, NULL),
('Badge Jujutsu Kaisen', 'goodies', 'jujutsu_kaisen', 'image/badge_jujutsu_kaisen.jpg', 27.90, NULL),
('Peruque Itadori', 'goodies', 'jujutsu_kaisen', 'image/peruque_itadori.jpg', 27.90, NULL),
('Book Itadori', 'goodies', 'jujutsu_kaisen', 'image/book_itadori.jpg', 45.90, NULL),
('Lampe Gojo', 'goodies', 'jujutsu_kaisen', 'image/lampe_gojo.jpg', 45.90, NULL),
('Lampe Rengoku', 'goodies', 'demon_slayer', 'image/lampe_rengoku.webp', 45.90, NULL),
('Lampe Tanjiro', 'goodies', 'demon_slayer', 'image/lampe_tanjiro.webp', 45.90, NULL),
('Lampe Zenitsu', 'goodies', 'demon_slayer', 'image/lampe_zenitsu.webp', 45.90, NULL),
('Lampe Inosuke', 'goodies', 'demon_slayer', 'image/lampe_inosuke.webp', 45.90, NULL),
('Lampe Demon Slayer', 'goodies', 'demon_slayer', 'image/lampe_demon_slayer.jpg', 45.90, NULL),
('Box Demon Slayer', 'goodies', 'demon_slayer', 'image/box_demon_slayer.jpg', 75.90, NULL),
('Sekai Saisoku no Isekai Ryokouki', 'manga', NULL, 'image/sekai_saisoku_no_isekai_ryokouki.jpg', 7.80, 'Lundi'),
('Ordeal', 'manga', NULL, 'image/ordeal.jpg', 7.80, 'Lundi'),
('Blue Box', 'manga', NULL, 'image/blue_box.jpg', 7.80, 'Lundi'),
('Nyaight of the Living Cat', 'manga', NULL, 'image/nyaight_of_the_living_cat.jpg', 7.80, 'Lundi'),
('Juvenile Detention Center', 'manga', NULL, 'image/juvenile_detention_center.jpg', 7.80, 'Lundi'),
('Maybe Meant', 'manga', NULL, 'image/maybe_meant.jpg', 7.80, 'Lundi'),
('Tonikaku Kuwai', 'manga', NULL, 'image/tonikaku_kuwai.jpeg', 7.80, 'Lundi'),
('To Your Eternity', 'manga', NULL, 'image/to_your_eternity.jpeg', 7.80, 'Lundi'),
('Yano Kun no', 'manga', NULL, 'image/yano_kun_no.jpg', 7.80, 'Mardi'),
('Return to Player', 'manga', NULL, 'image/return_to_player.jpg', 7.80, 'Mardi'),
('Manager Kim', 'manga', NULL, 'image/manager_kim.jpg', 7.80, 'Mardi'),
('Hero Without a Class', 'manga', NULL, 'image/hero_without_a_class.jpg', 7.80, 'Mardi'),
('Let''s Play', 'manga', NULL, 'image/lets_play.jpg', 7.80, 'Mardi'),
('Afterlife Inn Cooking', 'manga', NULL, 'image/afterlife_inn_cooking.jpg', 7.80, 'Mardi'),
('Rent a Girl', 'manga', NULL, 'image/rent_a_girl.jpg', 7.80, 'Mardi'),
('A Couple of Cuckoos', 'manga', NULL, 'image/a_couple_of_cuckoos.jpg', 7.80, 'Mardi'),
('99 Reinforced Wood Stick', 'manga', NULL, 'image/99_reinforced_wood_stick.jpeg', 7.80, 'Mercredi'),
('Baek', 'manga', NULL, 'image/baek.jpeg', 7.80, 'Mercredi'),
('Surviving the Game As', 'manga', NULL, 'image/surviving_the_game_as.jpeg', 7.80, 'Mercredi'),
('The Druid of Seoul Station', 'manga', NULL, 'image/the_druid_of_seoul_station.jpeg', 7.80, 'Mercredi'),
('The Mafia Nanny', 'manga', NULL, 'image/the_mafia_nanny.jpeg', 7.80, 'Mercredi'),
('Umamusume Cinderella Gray', 'manga', NULL, 'image/umamusume_cinderella_gray.jpeg', 7.80, 'Mercredi'),
('Blue Orchestra', 'manga', NULL, 'image/blue_orchestra.jpeg', 7.80, 'Mercredi'),
('Hero Ticket', 'manga', NULL, 'image/hero_ticket.jpeg', 7.80, 'Mercredi'),
('Dr. Stone', 'manga', NULL, 'image/dr_stone.jpeg', 7.90, 'Jeudi'),
('Futari Solo Camp', 'manga', NULL, 'image/futari_solo_camp.jpeg', 7.80, 'Jeudi'),
('Past the Monster Meat', 'manga', NULL, 'image/past_the_monster_meat.jpeg', 7.80, 'Jeudi'),
('The Rising of the Shield Hero', 'manga', NULL, 'image/the_rising_of_the_shield_hero.jpeg', 7.90, 'Jeudi'),
('I Was Reincarnated as the 7th Prince', 'manga', NULL, 'image/i_was_reincarnated_as_the_7th_prince.jpeg', 7.80, 'Jeudi'),
('Reborn as a Vending Machine', 'manga', NULL, 'image/reborn_as_a_vending_machine.jpeg', 7.80, 'Jeudi'),
('Dreaming Freedom', 'manga', NULL, 'image/dreaming_freedom.jpeg', 7.80, 'Jeudi'),
('Dragon Raja', 'manga', NULL, 'image/dragon_raja.jpeg', 7.90, 'Vendredi'),
('Cat''s Eyes 2025', 'manga', NULL, 'image/cats_eyes_2025.jpeg', 7.80, 'Vendredi'),
('Watari Kun no XX ga Houkai Sunzen', 'manga', NULL, 'image/watari_kun_no_xx_ga_houkai_sunzen.jpeg', 7.90, 'Vendredi'),
('Tsubasa Chronicle', 'manga', NULL, 'image/tsubasa_chronicle.jpeg', 7.90, 'Vendredi'),
('May I Ask for One Final Thing', 'manga', NULL, 'image/may_i_ask_for_one_final_thing.jpeg', 7.80, 'Vendredi'),
('One Piece', 'manga', NULL, 'image/one_piece.jpeg', 7.90, 'Vendredi'),
('Study Group', 'manga', NULL, 'image/study_group.jpeg', 7.80, 'Vendredi'),
('Lord of Mysteries', 'manga', NULL, 'image/lord_of_mysteries.jpeg', 7.90, 'Samedi'),
('Détective Conan', 'manga', NULL, 'image/detective_conan.jpeg', 7.90, 'Samedi'),
('A Wild Last Boss Appeared', 'manga', NULL, 'image/a_wild_last_boss_appeared.jpeg', 7.80, 'Samedi'),
('Silent Witch', 'manga', NULL, 'image/silent_witch.jpeg', 7.80, 'Samedi'),
('Kingdom', 'manga', NULL, 'image/kingdom.jpeg', 7.90, 'Samedi'),
('My Hero Academia', 'manga', NULL, 'image/my_hero_academia.jpeg', 7.90, 'Samedi'),
('Spy x Family', 'manga', NULL, 'image/spy_x_family.jpeg', 7.90, 'Samedi'),
('Let This Grieving Soul Retire', 'manga', NULL, 'image/let_this_grieving_soul_retire.jpeg', 7.80, 'Samedi'),
('Witch Watch', 'manga', NULL, 'image/witch_watch.jpeg', 7.90, 'Dimanche'),
('My Dress Up Darling', 'manga', NULL, 'image/my_dress_up_darling.jpeg', 7.90, 'Dimanche'),
('Rascal Does Not Dream of Bunny Girl Senpai', 'manga', NULL, 'image/rascal_does_not_dream_of_bunny_girl_senpai.jpeg', 8.50, 'Dimanche'),
('Gachiakuta', 'manga', NULL, 'image/gachiakuta.jpeg', 7.80, 'Dimanche'),
('Be a Princess Someday', 'manga', NULL, 'image/be_a_princess_someday.jpeg', 7.90, 'Dimanche'),
('Kikaijikake no Marie', 'manga', NULL, 'image/kikaijikake_no_marie.jpeg', 7.80, 'Dimanche'),
('Alma Chan wa Kazoku ni Naritai', 'manga', NULL, 'image/alma_chan_wa_kazoku_ni_naritai.jpeg', 7.90, 'Dimanche'),
('Dad is a Hero, Mom is a Spring, I''m a', 'manga', NULL, 'image/dad_is_a_hero_mom_is_a_spring_im_a.jpeg', 7.80, 'Dimanche'),
('Chain Saw', 'manga', NULL, 'image/chain_saw.jpg', 7.90, 'Sans jour fixe'),
('Fairy Tail 100 Years Quest', 'manga', NULL, 'image/fairy_tail_100_years_quest.jpg', 7.90, 'Sans jour fixe'),
('Four Knights of the Apocalypse', 'manga', NULL, 'image/four_knights_of_the_apocalypse.jpg', 8.50, 'Sans jour fixe'),
('Blue Lock', 'manga', NULL, 'image/blue_lock.jpg', 7.90, 'Sans jour fixe'),
('Embers', 'manga', NULL, 'image/embers.jpg', 7.80, 'Sans jour fixe'),
('I''m the Max Level Newbie', 'manga', NULL, 'image/im_the_max_level_newbie.jpg', 8.00, 'Sans jour fixe'),
('Infinite Mage', 'manga', NULL, 'image/infinite_mage.jpg', 7.90, 'Sans jour fixe'),
('Itchi the Witch', 'manga', NULL, 'image/itchi_the_witch.jpg', 7.50, 'Sans jour fixe'),
('Kaoru Hana wa Rin to Saku', 'manga', NULL, 'image/kaoru_hana_wa_rin_to_saku.jpg', 7.90, 'Sans jour fixe'),
('Lecteur Omniscient', 'manga', NULL, 'image/lecteur_omniscient.jpg', 8.00, 'Sans jour fixe'),
('Nano Machine', 'manga', NULL, 'image/nano_machine.jpg', 7.80, 'Sans jour fixe'),
('Nebula''s Civilation', 'manga', NULL, 'image/nebulas_civilation.jpg', 8.00, 'Sans jour fixe'),
('Pick Me Up', 'manga', NULL, 'image/pick_me_up.jpg', 7.90, 'Sans jour fixe'),
('Player', 'manga', NULL, 'image/player.jpg', 7.90, 'Sans jour fixe'),
('Player Who Returned 10000 Year Later', 'manga', NULL, 'image/player_who_returned_10000_year_later.jpg', 8.50, 'Sans jour fixe'),
('Reality Quest', 'manga', NULL, 'image/reality_quest.jpg', 7.90, 'Sans jour fixe'),
('Solo Leveling', 'manga', NULL, 'image/solo_leveling.jpeg', 8.50, 'Sans jour fixe'),
('Wind Breaker', 'manga', NULL, 'image/wind_breaker.jpg', 7.80, 'Sans jour fixe'),
('The Beginning After the End', 'manga', NULL, 'image/the_beginning_after_the_end.jpg', 8.50, 'Sans jour fixe'),
('Tougen Anki', 'manga', NULL, 'image/tougen_anki.jpg', 7.90, 'Sans jour fixe'),
('Shangri-La Frontier', 'manga', NULL, 'image/shangrila_frontier.jpeg', 8.00, 'Sans jour fixe'),
('Afro samourai', 'manga', NULL, 'image/afro_samourai.jpeg', 7.99, NULL),
('Boruto next generation tome 1', 'manga', NULL, 'image/boruto_next_generation_tome_1.jpg', 7.99, NULL),
('Capitaine tsubasa tome', 'manga', NULL, 'image/capitaine_tsubasa_tome.jpeg', 7.99, NULL),
('Dandadan tome', 'manga', NULL, 'image/dandadan_tome.jpeg', 7.99, NULL),
('Demon slayer tome', 'manga', NULL, 'image/demon_slayer_tome.jpeg', 7.99, NULL),
('Edens zero tome', 'manga', NULL, 'image/edens_zero_tome.jpeg', 7.99, NULL),
('Imouza tome 1', 'manga', NULL, 'image/imouza_tome_1.jpeg', 7.99, NULL),
('Jujutsu kaisen tome', 'manga', NULL, 'image/jujutsu_kaisen_tome.jpeg', 7.99, NULL),
('Kaiju n8 tome', 'manga', NULL, 'image/kaiju_n8_tome.jpeg', 7.99, NULL),
('La nuit des demons tome 1', 'manga', NULL, 'image/la_nuit_des_demons_tome_1.jpeg', 7.99, NULL),
('Mar tome', 'manga', NULL, 'image/mar_tome.jpg', 7.99, NULL),
('Marchen crown tome 1', 'manga', NULL, 'image/marchen_crown_tome_1.jpg', 7.99, NULL),
('Sakamoto days tome', 'manga', NULL, 'image/sakamoto_days_tome.jpeg', 7.99, NULL),
('Shuumatsu touring tome 1', 'manga', NULL, 'image/shuumatsu_touring_tome_1.jpeg', 7.99, NULL),
('Tojima wants to be a kamen rider tome 1', 'manga', NULL, 'image/tojima_wants_to_be_a_kamen_rider_tome_1.jpeg', 7.99, NULL),
('Dragon Ball', 'manga', NULL, 'image/dragon_ball.jpeg', 6.90, NULL),
('Dragon Ball Z', 'manga', NULL, 'image/dragon_ball_z.jpeg', 7.10, NULL),
('Naruto', 'manga', NULL, 'image/naruto.jpeg', 7.50, NULL),
('Naruto Shippuden', 'manga', NULL, 'image/naruto_shippuden.jpeg', 7.90, NULL),
('Bleach', 'manga', NULL, 'image/bleach.jpeg', 7.30, NULL),
('Pokémon', 'manga', NULL, 'image/pokemon.jpeg', 6.50, NULL),
('Ranma ½', 'manga', NULL, 'image/ranma.jpeg', 7.40, NULL),
('Yu-Gi-Oh', 'manga', NULL, 'image/yugioh.jpeg', 7.00, NULL),
('Great Teacher Onizuka', 'manga', NULL, 'image/great_teacher_onizuka.jpeg', 8.20, NULL),
('Death Note', 'manga', NULL, 'image/death_note.jpeg', 6.90, NULL),
('Hajime No Ippo', 'manga', NULL, 'image/hajime_no_ippo.jpeg', 8.90, NULL),
('Ken le Survivant', 'manga', NULL, 'image/ken_le_survivant.jpeg', 8.50, NULL),
('Gundam Wing', 'manga', NULL, 'image/gundam_wing.jpeg', 8.00, NULL),
('Full Metal Alchemist', 'manga', NULL, 'image/full_metal_alchemist.jpeg', 8.00, NULL),
('Fairy Tail', 'manga', NULL, 'image/fairy_tail.jpeg', 7.50, NULL),
('One Punch Man', 'manga', NULL, 'image/one_punch_man.jpeg', 8.50, NULL),
('Hunter-X-Hunter', 'manga', NULL, 'image/hunterxhunter.jpeg', 7.80, NULL),
('Moi Quand Je Me Reincarne En Slime', 'manga', NULL, 'image/moi_quand_je_me_reincarne_en_slime.jpeg', 7.80, NULL),
('Nicky Larson', 'manga', NULL, 'image/nicky_larson.jpeg', 7.80, NULL),
('Saint Seya Les Chevaliers Du Zodiaque', 'manga', NULL, 'image/saint_seya_les_chevaliers_du_zodiaque.jpeg', 7.80, NULL),
('Sailor-Moon', 'manga', NULL, 'image/sailormoon.jpeg', 7.80, NULL),
('Pop Naruto - Edition limitée', 'figurine', NULL, 'image/pop_naruto_edition_limitee.jpeg', 29.90, NULL),
('Figurine Itachi + Peluche Kuruma', 'figurine', NULL, 'image/figurine_itachi_peluche_kuruma.jpeg', 52.50, NULL),
('Figurine Jiraya', 'figurine', NULL, 'image/figurine_jiraya.jpeg', 25.90, NULL),
('Figurine Naruto Mode Emite', 'figurine', NULL, 'image/figurine_naruto_mode_emite.jpeg', 35.90, NULL),
('Coffret 16 one piece', 'goodies', 'one_piece', 'image/coffret_16_one_piece.jpeg', 57.99, NULL),
('Lots porte cle jujutsu kaisen', 'goodies', 'jujutsu_kaisen', 'image/lots_porte_cle_jujutsu_kaisen.jpeg', 17.99, NULL),
('Bracelet sharingan', 'goodies', 'naruto', 'image/bracelet_sharingan.jpeg', 67.99, NULL),
('Coffret 28 naruto', 'goodies', 'naruto', 'image/coffret_28_naruto.jpeg', 67.99, NULL),
('Lampe kakashi 3d', 'goodies', 'naruto', 'image/lampe_kakashi_3d.webp', 67.99, NULL),
('Masque haku', 'goodies', 'naruto', 'image/masque_haku.jpeg', 67.99, NULL),
('Porte cle naruto', 'goodies', 'naruto', 'image/porte_cle_naruto.jpeg', 67.99, NULL),
('Cahier dbs goku ssb vs hit', 'goodies', 'dragon_ball', 'image/cahier_dbs_goku_ssb_vs_hit.jpg', 27.99, NULL),
('Cahier dbs kamehameha', 'goodies', 'dragon_ball', 'image/cahier_dbs_kamehameha.jpg', 27.99, NULL),
('Peluche hit', 'goodies', 'dragon_ball', 'image/peluche_hit.jpg', 27.99, NULL),
('Poster broly', 'goodies', 'dragon_ball', 'image/poster_broly.jpg', 27.99, NULL),
('Poster broly vs vegeta ssb goku ssb', 'goodies', 'dragon_ball', 'image/poster_broly_vs_vegeta_ssb_goku_ssb.jpg', 27.99, NULL),
('Poster goku ui', 'goodies', 'dragon_ball', 'image/poster_goku_ui.jpg', 27.99, NULL),
('Poster shenron', 'goodies', 'dragon_ball', 'image/poster_shenron.jpg', 27.99, NULL),
('Radar dbz', 'goodies', 'dragon_ball', 'image/radar_dbz.jpg', 27.99, NULL),
('Set 2 posters goku', 'goodies', 'dragon_ball', 'image/set_2_posters_goku.jpg', 27.99, NULL),
('Jeu de société Naruto', 'goodies', 'naruto', 'image/jeu_de_societe_naruto.jpeg', 56.50, NULL),
('Katana Konoha', 'goodies', 'naruto', 'image/katana_konoha.jpeg', 74.90, NULL),
('Sac Naruto', 'goodies', 'naruto', 'image/sac_naruto.jpeg', 34.90, NULL),
('Porte clé Pop Naruto', 'goodies', 'naruto', 'image/porte_cle_pop_naruto.jpeg', 14.90, NULL),
('Mug Naruto Equipe 7', 'vaisselle', 'naruto', 'image/mug_naruto_equipe_7.jpeg', 9.90, NULL),
('Bandeau Sasuke', 'goodies', 'naruto', 'image/bandeau_sasuke.jpeg', 44.90, NULL),
('Kunai Naruto', 'goodies', 'naruto', 'image/kunai_naruto.jpeg', 54.90, NULL),
('Figurine Satoru Gojo', 'figurine', NULL, 'image/figurine_satoru_gojo.jpeg', 17.80, NULL),
('figurine acnologia forme humaine', 'figurine', NULL, 'image/figurine_acnologia_forme_humaine.jpg', 57.99, NULL),
('figurine al et ed', 'figurine', NULL, 'image/figurine_al_et_ed.jpg', 57.99, NULL),
('figurine all might', 'figurine', NULL, 'image/figurine_all_might.jpg', 57.99, NULL),
('figurine all might energie', 'figurine', NULL, 'image/figurine_all_might_energie.jpg', 57.99, NULL),
('figurine all might fight', 'figurine', NULL, 'image/figurine_all_might_fight.jpg', 57.99, NULL),
('figurine alphonse elric', 'figurine', NULL, 'image/figurine_alphonse_elric.jpg', 57.99, NULL),
('figurine armure sagitaire', 'figurine', NULL, 'image/figurine_armure_sagitaire.jpg', 57.99, NULL),
('figurine bakugo', 'figurine', NULL, 'image/figurine_bakugo.jpg', 57.99, NULL),
('figurine black asta', 'figurine', NULL, 'image/figurine_black_asta.jpg', 57.99, NULL),
('figurine cha hae', 'figurine', NULL, 'image/figurine_cha_hae.jpg', 57.99, NULL),
('figurine deku', 'figurine', NULL, 'image/figurine_deku.jpg', 57.99, NULL),
('figurine dr stone', 'figurine', NULL, 'image/figurine_dr_stone.jpg', 57.99, NULL),
('figurine edward elric', 'figurine', NULL, 'image/figurine_edward_elric.jpg', 57.99, NULL),
('figurine endeavor', 'figurine', NULL, 'image/figurine_endeavor.jpg', 57.99, NULL),
('figurine erza scarlette', 'figurine', NULL, 'image/figurine_erza_scarlette.jpg', 57.99, NULL),
('figurine gajil', 'figurine', NULL, 'image/figurine_gajil.jpg', 57.99, NULL),
('figurine garou', 'figurine', NULL, 'image/figurine_garou.jpg', 57.99, NULL),
('figurine gear 5 luffy', 'figurine', NULL, 'image/figurine_gear_5_luffy.jpg', 57.99, NULL),
('figurine genos', 'figurine', NULL, 'image/figurine_genos.jpg', 57.99, NULL),
('figurine goku ss', 'figurine', NULL, 'image/figurine_goku_ss.jpg', 57.99, NULL),
('figurine gol d roger', 'figurine', NULL, 'image/figurine_gol_d_roger.jpeg', 57.99, NULL),
('figurine gon attaque', 'figurine', NULL, 'image/figurine_gon_attaque.jpg', 57.99, NULL),
('figurine grey', 'figurine', NULL, 'image/figurine_grey.jpg', 57.99, NULL),
('figurine gyoso', 'figurine', NULL, 'image/figurine_gyoso.jpg', 57.99, NULL),
('figurine hisoka', 'figurine', NULL, 'image/figurine_hisoka.jpg', 57.99, NULL),
('figurine izuku midoria et eri', 'figurine', NULL, 'image/figurine_izuku_midoria_et_eri.jpg', 57.99, NULL),
('figurine izuku midoria tenue', 'figurine', NULL, 'image/figurine_izuku_midoria_tenue.jpg', 57.99, NULL),
('figurine kakashi', 'figurine', NULL, 'image/figurine_kakashi.jpeg', 57.99, NULL),
('figurine kilua electrique', 'figurine', NULL, 'image/figurine_kilua_electrique.jpg', 57.99, NULL),
('figurine king bradley', 'figurine', NULL, 'image/figurine_king_bradley.jpg', 57.99, NULL),
('figurine kiojuro', 'figurine', NULL, 'image/figurine_kiojuro.jpeg', 57.99, NULL),
('figurine kurapika', 'figurine', NULL, 'image/figurine_kurapika.jpg', 57.99, NULL),
('figurine l et watari', 'figurine', NULL, 'image/figurine_l_et_watari.jpg', 57.99, NULL),
('figurine leo', 'figurine', NULL, 'image/figurine_leo.jpg', 57.99, NULL),
('figurine light', 'figurine', NULL, 'image/figurine_light.jpg', 57.99, NULL),
('figurine light et ryuk', 'figurine', NULL, 'image/figurine_light_et_ryuk.jpg', 57.99, NULL),
('figurine lucy et aquaruis', 'figurine', NULL, 'image/figurine_lucy_et_aquaruis.jpg', 57.99, NULL),
('figurine lucy et happy', 'figurine', NULL, 'image/figurine_lucy_et_happy.jpg', 57.99, NULL),
('figurine luffy chopper', 'figurine', NULL, 'image/figurine_luffy_chopper.jpeg', 57.99, NULL),
('figurine luxus', 'figurine', NULL, 'image/figurine_luxus.jpg', 57.99, NULL),
('figurine meruem', 'figurine', NULL, 'image/figurine_meruem.jpg', 57.99, NULL),
('figurine minato', 'figurine', NULL, 'image/figurine_minato.jpeg', 57.99, NULL),
('figurine misa', 'figurine', NULL, 'image/figurine_misa.jpg', 57.99, NULL),
('figurine misa et ren', 'figurine', NULL, 'image/figurine_misa_et_ren.jpg', 57.99, NULL),
('figurine momo', 'figurine', NULL, 'image/figurine_momo.jpg', 57.99, NULL),
('figurine naruto rasengan', 'figurine', NULL, 'image/figurine_naruto_rasengan.jpeg', 57.99, NULL),
('figurine naruto sasuke', 'figurine', NULL, 'image/figurine_naruto_sasuke.jpeg', 57.99, NULL),
('figurine natsu', 'figurine', NULL, 'image/figurine_natsu.jpg', 57.99, NULL),
('figurine natsu et lucy', 'figurine', NULL, 'image/figurine_natsu_et_lucy.jpg', 57.99, NULL),
('figurine natsu feu', 'figurine', NULL, 'image/figurine_natsu_feu.jpg', 57.99, NULL),
('figurine natsu grey erza', 'figurine', NULL, 'image/figurine_natsu_grey_erza.jpg', 57.99, NULL),
('figurine ochako uraraka', 'figurine', NULL, 'image/figurine_ochako_uraraka.jpg', 57.99, NULL),
('figurine okarun', 'figurine', NULL, 'image/figurine_okarun.jpg', 57.99, NULL),
('figurine okarun possede', 'figurine', NULL, 'image/figurine_okarun_possede.jpg', 57.99, NULL),
('figurine pop all might', 'figurine', NULL, 'image/figurine_pop_all_might.jpg', 57.99, NULL),
('figurine pop alphonse elric', 'figurine', NULL, 'image/figurine_pop_alphonse_elric.jpg', 57.99, NULL),
('figurine pop asta', 'figurine', NULL, 'image/figurine_pop_asta.jpg', 57.99, NULL),
('figurine pop bakugo katsuki', 'figurine', NULL, 'image/figurine_pop_bakugo_katsuki.jpg', 57.99, NULL),
('figurine pop beru', 'figurine', NULL, 'image/figurine_pop_beru.jpg', 57.99, NULL),
('figurine pop black asta', 'figurine', NULL, 'image/figurine_pop_black_asta.jpg', 57.99, NULL),
('figurine pop boros', 'figurine', NULL, 'image/figurine_pop_boros.jpg', 57.99, NULL),
('figurine pop cha hae in', 'figurine', NULL, 'image/figurine_pop_cha_hae_in.jpg', 57.99, NULL),
('figurine pop daby', 'figurine', NULL, 'image/figurine_pop_daby.jpg', 57.99, NULL),
('figurine pop edward elric', 'figurine', NULL, 'image/figurine_pop_edward_elric.jpg', 57.99, NULL),
('figurine pop fuegoleon', 'figurine', NULL, 'image/figurine_pop_fuegoleon.jpg', 57.99, NULL),
('figurine pop garou', 'figurine', NULL, 'image/figurine_pop_garou.jpg', 57.99, NULL),
('figurine pop genos', 'figurine', NULL, 'image/figurine_pop_genos.jpg', 57.99, NULL),
('figurine pop gon', 'figurine', NULL, 'image/figurine_pop_gon.jpg', 57.99, NULL),
('figurine pop greed', 'figurine', NULL, 'image/figurine_pop_greed.jpg', 57.99, NULL),
('figurine pop grey devil slayer', 'figurine', NULL, 'image/figurine_pop_grey_devil_slayer.jpg', 57.99, NULL),
('figurine pop happy', 'figurine', NULL, 'image/figurine_pop_happy.jpg', 57.99, NULL),
('figurine pop hisoka', 'figurine', NULL, 'image/figurine_pop_hisoka.jpg', 57.99, NULL),
('figurine pop igris', 'figurine', NULL, 'image/figurine_pop_igris.jpg', 57.99, NULL),
('figurine pop iron', 'figurine', NULL, 'image/figurine_pop_iron.jpg', 57.99, NULL),
('figurine pop izuku midoria', 'figurine', NULL, 'image/figurine_pop_izuku_midoria.jpg', 57.99, NULL),
('figurine pop izuku midoria et eri', 'figurine', NULL, 'image/figurine_pop_izuku_midoria_et_eri.jpg', 57.99, NULL),
('figurine pop izumi curtis', 'figurine', NULL, 'image/figurine_pop_izumi_curtis.jpg', 57.99, NULL),
('figurine pop julius', 'figurine', NULL, 'image/figurine_pop_julius.jpg', 57.99, NULL),
('figurine pop kilua', 'figurine', NULL, 'image/figurine_pop_kilua.jpg', 57.99, NULL),
('figurine pop kurapika', 'figurine', NULL, 'image/figurine_pop_kurapika.jpg', 57.99, NULL),
('figurine pop l', 'figurine', NULL, 'image/figurine_pop_l.jpg', 57.99, NULL),
('figurine pop licht', 'figurine', NULL, 'image/figurine_pop_licht.jpg', 57.99, NULL),
('figurine pop light', 'figurine', NULL, 'image/figurine_pop_light.jpg', 57.99, NULL),
('figurine pop luxus', 'figurine', NULL, 'image/figurine_pop_luxus.jpg', 57.99, NULL),
('figurine pop meruem', 'figurine', NULL, 'image/figurine_pop_meruem.jpg', 57.99, NULL),
('figurine pop misa', 'figurine', NULL, 'image/figurine_pop_misa.jpg', 57.99, NULL),
('figurine pop momo', 'figurine', NULL, 'image/figurine_pop_momo.jpg', 57.99, NULL),
('figurine pop natsu', 'figurine', NULL, 'image/figurine_pop_natsu.jpg', 57.99, NULL),
('figurine pop netero', 'figurine', NULL, 'image/figurine_pop_netero.jpg', 57.99, NULL),
('figurine pop nezuko', 'figurine', NULL, 'image/figurine_pop_nezuko.jpeg', 57.99, NULL),
('figurine pop noelle', 'figurine', NULL, 'image/figurine_pop_noelle.jpg', 57.99, NULL),
('figurine pop noelle valkyrie dress', 'figurine', NULL, 'image/figurine_pop_noelle_valkyrie_dress.jpg', 57.99, NULL),
('figurine pop nozel', 'figurine', NULL, 'image/figurine_pop_nozel.jpg', 57.99, NULL),
('figurine pop ochaco uraraka', 'figurine', NULL, 'image/figurine_pop_ochaco_uraraka.jpg', 57.99, NULL),
('figurine pop okarun possede', 'figurine', NULL, 'image/figurine_pop_okarun_possede.jpg', 57.99, NULL),
('figurine pop olivier armstrong', 'figurine', NULL, 'image/figurine_pop_olivier_armstrong.jpg', 57.99, NULL),
('figurine pop roy mustang', 'figurine', NULL, 'image/figurine_pop_roy_mustang.jpg', 57.99, NULL),
('figurine pop ryuk', 'figurine', NULL, 'image/figurine_pop_ryuk.jpg', 57.99, NULL),
('figurine pop saitama', 'figurine', NULL, 'image/figurine_pop_saitama.jpg', 57.99, NULL),
('figurine pop scar', 'figurine', NULL, 'image/figurine_pop_scar.jpg', 57.99, NULL),
('figurine pop seiko', 'figurine', NULL, 'image/figurine_pop_seiko.jpg', 57.99, NULL),
('figurine pop shoto todoroki', 'figurine', NULL, 'image/figurine_pop_shoto_todoroki.jpg', 57.99, NULL),
('figurine pop sung jin woo', 'figurine', NULL, 'image/figurine_pop_sung_jin_woo.jpg', 57.99, NULL),
('figurine pop tanjiro', 'figurine', NULL, 'image/figurine_pop_tanjiro.jpeg', 57.99, NULL),
('figurine pop tanjiro feu', 'figurine', NULL, 'image/figurine_pop_tanjiro_feu.jpeg', 57.99, NULL),
('figurine pop tatsumaki', 'figurine', NULL, 'image/figurine_pop_tatsumaki.jpg', 57.99, NULL),
('figurine pop tomura shigaraki', 'figurine', NULL, 'image/figurine_pop_tomura_shigaraki.jpg', 57.99, NULL),
('figurine pop william', 'figurine', NULL, 'image/figurine_pop_william.jpg', 57.99, NULL),
('figurine pop yami', 'figurine', NULL, 'image/figurine_pop_yami.jpg', 57.99, NULL),
('figurine pop yuno', 'figurine', NULL, 'image/figurine_pop_yuno.jpg', 57.99, NULL),
('figurine pop yuno zephyr', 'figurine', NULL, 'image/figurine_pop_yuno_zephyr.jpg', 57.99, NULL),
('figurine pop zeref', 'figurine', NULL, 'image/figurine_pop_zeref.jpg', 57.99, NULL),
('figurine roy mustang', 'figurine', NULL, 'image/figurine_roy_mustang.jpg', 57.99, NULL),
('figurine ryuk', 'figurine', NULL, 'image/figurine_ryuk.jpg', 57.99, NULL),
('figurine saitama', 'figurine', NULL, 'image/figurine_saitama.jpg', 57.99, NULL),
('figurine saitama detruit monstre', 'figurine', NULL, 'image/figurine_saitama_detruit_monstre.jpg', 57.99, NULL),
('figurine secre', 'figurine', NULL, 'image/figurine_secre.jpg', 57.99, NULL),
('figurine seiko', 'figurine', NULL, 'image/figurine_seiko.jpg', 57.99, NULL),
('figurine shoto todoroki', 'figurine', NULL, 'image/figurine_shoto_todoroki.jpg', 57.99, NULL),
('figurine sung jin woo', 'figurine', NULL, 'image/figurine_sung_jin_woo.jpg', 57.99, NULL),
('figurine taka', 'figurine', NULL, 'image/figurine_taka.jpg', 57.99, NULL),
('figurine tomura shigaraki', 'figurine', NULL, 'image/figurine_tomura_shigaraki.jpg', 57.99, NULL),
('figurine wendy et gadjil', 'figurine', NULL, 'image/figurine_wendy_et_gadjil.jpg', 57.99, NULL),
('figurine winry rockbelle', 'figurine', NULL, 'image/figurine_winry_rockbelle.jpg', 57.99, NULL),
('figurine yami', 'figurine', NULL, 'image/figurine_yami.jpg', 57.99, NULL),
('figurine yuno', 'figurine', NULL, 'image/figurine_yuno.jpg', 57.99, NULL),
('figurine yuno attaque', 'figurine', NULL, 'image/figurine_yuno_attaque.jpg', 57.99, NULL),
('figurines gogeta janemba match makers', 'figurine', NULL, 'image/figurines_gogeta_janemba_match_makers.jpg', 57.99, NULL),
('figurines gohan enfant ss2 vs cell match makers', 'figurine', NULL, 'image/figurines_gohan_enfant_ss2_vs_cell_match_makers.jpg', 57.99, NULL),
('figurines gon vs hisoka', 'figurine', NULL, 'image/figurines_gon_vs_hisoka.jpg', 57.99, NULL),
('figurines gon vs kilua', 'figurine', NULL, 'image/figurines_gon_vs_kilua.jpg', 57.99, NULL),
('figurine jellal', 'figurine', NULL, 'image/fugurine_jellal.jpg', 57.99, NULL),
('Lampe Satoru Gojo', 'goodies', 'jujutsu_kaisen', 'image/lampe_satoru_gojo.jpeg', 27.80, NULL),
('Sac à Dos Jujutsu Kaisen', 'goodies', 'jujutsu_kaisen', 'image/sac_a_dos_jujutsu_kaisen.jpeg', 47.80, NULL),
('Lots Bagues Jujutsu Kaisen', 'goodies', 'jujutsu_kaisen', 'image/lots_bagues_jujutsu_kaisen.jpeg', 37.80, NULL),
('Mug Satoru Gojo', 'goodies', 'jujutsu_kaisen', 'image/mug_satoru_gojo.jpeg', 18.80, NULL),
('Figurine Pop Sukuna', 'figurine', NULL, 'image/figurine_pop_sukuna.jpeg', 27.80, NULL),
('Figurine Pop Megumi', 'figurine', NULL, 'image/figurine_pop_megumi.jpeg', 27.80, NULL),
('Bateau Thousant Sunny', 'goodies', 'one_piece', 'image/bateau_thousant_sunny.jpeg', 87.80, NULL),
('Coffre au Trésor One Piece', 'goodies', 'one_piece', 'image/coffre_au_tresor_one_piece.jpeg', 97.80, NULL),
('Verre One Piece', 'goodies', 'one_piece', 'image/verre_one_piece.jpeg', 7.80, NULL),
('Assiette pokemon', 'vaisselle', NULL, 'image/assiette_pokemon.jpg', 37.99, NULL),
('Bol dragon ball z', 'vaisselle', NULL, 'image/bol_dragon_ball_z.jpg', 37.99, NULL),
('Bol equipe 7', 'vaisselle', NULL, 'image/bol_equipe_7.jpeg', 37.99, NULL),
('Bol itachi', 'vaisselle', NULL, 'image/bol_itachi.jpeg', 37.99, NULL),
('Mug broly', 'vaisselle', NULL, 'image/mug_broly.jpg', 37.99, NULL),
('Mug doight sukuna', 'vaisselle', NULL, 'image/mug_doight_sukuna.jpg', 37.99, NULL),
('Mug dr stone', 'vaisselle', NULL, 'image/mug_dr_stone.jpg', 37.99, NULL),
('Mug itadori', 'vaisselle', NULL, 'image/mug_itadori.gif', 37.99, NULL),
('Mug kaido', 'vaisselle', NULL, 'image/mug_kaido.jpg', 37.99, NULL),
('Mug luffy gear 5', 'vaisselle', NULL, 'image/mug_luffy_gear_5.jpg', 37.99, NULL),
('Mug luffy gear 5 wanted', 'vaisselle', NULL, 'image/mug_luffy_gear_5_wanted.jpg', 37.99, NULL),
('Mug majin vegeta', 'vaisselle', NULL, 'image/mug_majin_vegeta.jpg', 37.99, NULL),
('Mug naruto', 'vaisselle', NULL, 'image/mug_naruto.jpg', 37.99, NULL),
('Mug naruto 20ans', 'vaisselle', NULL, 'image/mug_naruto_20ans.jpg', 37.99, NULL),
('Set 6 verre dbz', 'vaisselle', NULL, 'image/set_6_verre_dbz.jpg', 37.99, NULL),
('Fruits des Demons', 'goodies', 'one_piece', 'image/fruits_des_demons.jpeg', 47.80, NULL),
('Peluche Fruit du Démon', 'goodies', 'one_piece', 'image/peluche_fruit_du_demon.jpeg', 29.80, NULL),
('Chapeau Luffy', 'goodies', 'one_piece', 'image/chapeau_luffy.jpeg', 54.80, NULL),
('Support Portable Luffy Gear 5', 'goodies', 'one_piece', 'image/support_portable_luffy_gear_5.jpeg', 25.80, NULL),
('Coque Portable One Piece', 'goodies', 'one_piece', 'image/coque_portable_one_piece.jpeg', 17.80, NULL),
('Sac à Dos One Piece', 'goodies', 'one_piece', 'image/sac_a_dos_one_piece.jpeg', 45.80, NULL),
('Lots Mugs One Piece', 'goodies', 'one_piece', 'image/lots_mugs_one_piece.jpeg', 77.80, NULL),
('Lampe Luffy Gear 5', 'goodies', 'one_piece', 'image/lampe_luffy_gear_5.jpeg', 44.80, NULL),
('Bague One Piece', 'goodies', 'one_piece', 'image/bague_one_piece.jpeg', 25.80, NULL),
('Porte Feuille One Piece', 'goodies', 'one_piece', 'image/porte_feuille_one_piece.jpeg', 45.80, NULL),
('Manette PS5 One Piece', 'goodies', 'one_piece', 'image/manette_ps5_one_piece.jpeg', 125.80, NULL),
('Figurine Led Luffy Gear 5', 'figurine', NULL, 'image/figurine_led_luffy_gear_5.jpeg', 67.80, NULL),
('Figurine Pop Luffy', 'figurine', NULL, 'image/figurine_pop_luffy.jpeg', 27.80, NULL),
('Figurine Ace', 'figurine', NULL, 'image/figurine_ace.jpeg', 27.80, NULL),
('Figurine Jinbe', 'figurine', NULL, 'image/figurine_jinbe.jpeg', 37.80, NULL),
('Figurine Ener', 'figurine', NULL, 'image/figurine_ener.jpeg', 37.80, NULL),
('Figurine Pop Kaido', 'figurine', NULL, 'image/figurine_pop_kaido.jpeg', 27.80, NULL),
('Figurine Luffy Gear 5', 'figurine', NULL, 'image/figurine_luffy_gear_5.jpeg', 39.80, NULL),
('Figurine Mihawk', 'figurine', NULL, 'image/figurine_mihawk.jpeg', 39.80, NULL),
('Figurine Pop Zoro', 'figurine', NULL, 'image/figurine_pop_zoro.jpeg', 27.80, NULL),
('Figurine Barbe Noir', 'figurine', NULL, 'image/figurine_barbe_noir.jpeg', 37.80, NULL),
('Lots Portes Clés Demon Slayer', 'goodies', 'demon_slayer', 'image/lots_portes_cles_demon_slayer.jpeg', 27.80, NULL),
('Katana Tanjiro', 'goodies', 'demon_slayer', 'image/katana_tanjiro.jpg', 107.80, NULL),
('Coffret 15 Piece Demon Slayer', 'goodies', 'demon_slayer', 'image/coffret_15_piece_demon_slayer.jpeg', 79.80, NULL),
('Coffret Demon Slayer', 'goodies', 'demon_slayer', 'image/coffret_demon_slayer.jpeg', 59.80, NULL),
('Figurine Tanjiro', 'figurine', NULL, 'image/figurine_tanjiro.jpeg', 37.90, NULL),
('Figurine Pop Tanjiro Nezuko', 'figurine', NULL, 'image/figurine_pop_tanjiro_nezuko.jpeg', 39.80, NULL),
('Figurine Nezuko', 'figurine', NULL, 'image/figurine_nezuko.jpeg', 29.90, NULL),
('Figurine Inosuke', 'figurine', NULL, 'image/figurine_inosuke.jpeg', 29.80, NULL),
('Figurine Sabito', 'figurine', NULL, 'image/figurine_sabito.jpeg', 29.80, NULL),
('Figurine Tengen', 'figurine', NULL, 'image/figurine_tengen.jpeg', 29.80, NULL),
('Figurine Tomyoka', 'figurine', NULL, 'image/figurine_tomyoka.jpeg', 29.80, NULL),
('Figurine Muichiro', 'figurine', NULL, 'image/figurine_muichiro.jpeg', 29.80, NULL),
('Figurine Sanemi', 'figurine', NULL, 'image/figurine_sanemi.jpeg', 29.80, NULL),
('Figurine Kanroji', 'figurine', NULL, 'image/figurine_kanroji.jpg', 29.80, NULL),
('Figurine Zenitsu', 'figurine', NULL, 'image/figurine_zenitsu.jpeg', 29.80, NULL),
('Figurine Pop Goku Ultra Instinct', 'figurine', NULL, 'image/figurine_pop_goku_ultra_instinct.jpg', 27.90, NULL),
('Figurine Pop M Vegeta', 'figurine', NULL, 'image/figurine_pop_m_vegeta.jpg', 27.90, NULL),
('Figurine Gogeta SS4', 'figurine', NULL, 'image/figurine_gogeta_ss4.jpg', 37.80, NULL),
('Figurine Broly Fullpower', 'figurine', NULL, 'image/figurine_broly_fullpower.jpg', 37.90, NULL),
('Figurine Trunks SS', 'figurine', NULL, 'image/figurine_trunks_ss.jpg', 39.90, NULL),
('Figurine Freezer', 'figurine', NULL, 'image/figurine_freezer.jpg', 7.80, NULL),
('Figurine Son Goku SS3', 'figurine', NULL, 'image/figurine_son_goku_ss3.jpg', 39.90, NULL),
('Figurine Goku UI Vs Jiren', 'figurine', NULL, 'image/figurine_goku_ui_vs_jiren.jpg', 67.80, NULL),
('Figurine Majin Buu', 'figurine', NULL, 'image/figurine_majin_buu.jpg', 37.80, NULL),
('Figurine Goten Trunks Fusion', 'figurine', NULL, 'image/figurine_goten_trunks_fusion.jpg', 49.80, NULL),
('Figurine Gotenks SS Ghost', 'figurine', NULL, 'image/figurine_gotenks_ss_ghost.jpg', 39.80, NULL),
('Figurine Gotenks SS3', 'figurine', NULL, 'image/figurine_gotenks_ss3.jpg', 47.80, NULL),
('Figurine Son Goku SSG', 'figurine', NULL, 'image/figurine_son_goku_ssg.jpg', 47.80, NULL),
('Figurine Son Goku SSB', 'figurine', NULL, 'image/figurine_son_goku_ssb.jpg', 47.80, NULL),
('Figurine Vegeta SSB', 'figurine', NULL, 'image/figurine_vegeta_ssb.jpg', 47.80, NULL),
('Figurine Baby Vegeta SS2', 'figurine', NULL, 'image/figurine_baby_vegeta_ss2.jpg', 47.80, NULL),
('Figurine Vegeto SS', 'figurine', NULL, 'image/figurine_vegeto_ss.jpg', 59.80, NULL),
('Figurine Gogeta SS', 'figurine', NULL, 'image/figurine_gogeta_ss.jpg', 47.80, NULL),
('Figurine Broly SS2', 'figurine', NULL, 'image/figurine_broly_ss2.jpg', 47.80, NULL),
('Figurine Metal Cooler', 'figurine', NULL, 'image/figurine_metal_cooler.jpg', 43.80, NULL),
('Figurine Black Goku', 'figurine', NULL, 'image/figurine_black_goku.jpg', 47.80, NULL),
('Figurine Beerus', 'figurine', NULL, 'image/figurine_beerus.jpg', 47.80, NULL),
('Tapis de Bureau Dragon Ball Super', 'goodies', 'dragon_ball', 'image/tapis_de_bureau_dragon_ball_super.jpg', 25.80, NULL),
('Sac Dragon Ball Super', 'goodies', 'dragon_ball', 'image/sac_dragon_ball_super.jpg', 18.80, NULL),
('Sac de Sport Dragon Ball Z', 'goodies', 'dragon_ball', 'image/sac_de_sport_dragon_ball_z.jpg', 35.80, NULL),
('Sac à Dos Goku', 'goodies', 'dragon_ball', 'image/sac_a_dos_goku.jpg', 29.80, NULL),
('Puzzle 1000 Pieces Dragon Ball Z', 'goodies', 'dragon_ball', 'image/puzzle_1000_pieces_dragon_ball_z.jpg', 55.80, NULL),
('Jeu de 54 Cartes Dragon Ball Z', 'goodies', 'dragon_ball', 'image/jeu_de_54_cartes_dragon_ball_z.jpg', 25.80, NULL),
('Uno Dragon Ball Z', 'goodies', 'dragon_ball', 'image/uno_dragon_ball_z.jpg', 45.80, NULL),
('Jeu de 7 Familles Dragon Ball Z', 'goodies', 'dragon_ball', 'image/jeu_de_7_familles_dragon_ball_z.jpg', 25.80, NULL),
('Boite à Musique Tapion', 'goodies', 'dragon_ball', 'image/boite_a_musique_tapion.jpg', 59.80, NULL),
('Coffret 7 Boules de Cristal Dragon Ball Z', 'goodies', 'dragon_ball', 'image/coffret_7_boules_de_cristal_dragon_ball_z.jpg', 75.80, NULL),
('Boule de Cristal 2 Etoiles Dragon Ball Z', 'goodies', 'dragon_ball', 'image/boule_de_cristal_2_etoiles_dragon_ball_z.jpg', 21.80, NULL),
('Mug Thermique Gohan vs Cell', 'vaisselle', NULL, 'image/mug_thermique_gohan_vs_cell.jpg', 25.80, NULL),
('Mug Broly SS2', 'vaisselle', NULL, 'image/mug_broly_ss2.jpg', 21.80, NULL),
('Mug Goku', 'vaisselle', NULL, 'image/mug_goku.jpg', 21.80, NULL),
('Mug Hit', 'vaisselle', NULL, 'image/mug_hit.jpg', 21.80, NULL),
('Boite à Cookies Kamehouse Dragon Ball Z', 'goodies', 'dragon_ball', 'image/boite_a_cookies_kamehouse_dragon_ball_z.jpg', 75.80, NULL),
('Porte Cle Goku SSB', 'goodies', 'dragon_ball', 'image/porte_cle_goku_ssb.jpg', 11.80, NULL),
('Porte Cle Pop Goku SS4', 'goodies', 'dragon_ball', 'image/porte_cle_pop_goku_ss4.jpg', 15.80, NULL),
('Porte Cle Radar Dragon Ball Z', 'goodies', 'dragon_ball', 'image/porte_cle_radar_dragon_ball_z.jpg', 11.80, NULL),
('Peluche Nuage Magique Dragon Ball Z', 'goodies', 'dragon_ball', 'image/peluche_nuage_magique_dragon_ball_z.jpg', 33.80, NULL),
('Lots Figurines Dragon Ball Z', 'goodies', 'dragon_ball', 'image/lots_figurines_dragon_ball_z.jpg', 55.80, NULL),
('Bol Chapeau Luffy', 'vaisselle', NULL, 'image/bol_chapeau_luffy.jpg', 37.90, NULL),
('Mug One Piece', 'vaisselle', NULL, 'image/mug_one_piece.jpg', 35.90, NULL),
('Tasse et Bol One Piece', 'vaisselle', NULL, 'image/tasse_et_bol_one_piece.jpg', 45.50, NULL),
('Bol Drapeau One Piece', 'vaisselle', NULL, 'image/bol_drapeau_one_piece.jpg', 35.80, NULL),
('Assiette One Piece', 'vaisselle', NULL, 'image/assiette_one_piece.jpg', 220.90, NULL),
('Mug Thermique One Piece Wanted', 'vaisselle', NULL, 'image/mug_thermique_one_piece_wanted.jpg', 38.80, NULL),
('Mug Luffy Gear 5 Attaque', 'vaisselle', NULL, 'image/mug_luffy_gear_5_attaque.jpg', 27.90, NULL),
('Mug Monkey D Luffy', 'vaisselle', NULL, 'image/mug_monkey_d_luffy.jpg', 27.80, NULL),
('Mug Luffy Zoro Chopper', 'vaisselle', NULL, 'image/mug_luffy_zoro_chopper.jpg', 27.80, NULL),
('Mug Chopper', 'vaisselle', NULL, 'image/mug_chopper.jpg', 27.80, NULL),
('Mug Garp', 'vaisselle', NULL, 'image/mug_garp.jpg', 27.80, NULL),
('Mug Barbe Noir', 'vaisselle', NULL, 'image/mug_barbe_noir.jpg', 27.80, NULL),
('Mug Trafalgar Law', 'vaisselle', NULL, 'image/mug_trafalgar_law.jpg', 27.80, NULL),
('Bol Konoha', 'vaisselle', NULL, 'image/bol_konoha.jpg', 32.80, NULL),
('Bol Akatsuki', 'vaisselle', NULL, 'image/bol_akatsuki.jpg', 32.80, NULL),
('Verre Akatsuki', 'vaisselle', NULL, 'image/verre_akatsuki.jpg', 35.80, NULL),
('Verre Uchiha', 'vaisselle', NULL, 'image/verre_uchiha.jpg', 35.80, NULL),
('Mug Thermique Sasuke Uchiha', 'vaisselle', NULL, 'image/mug_thermique_sasuke_uchiha.jpg', 38.80, NULL),
('Mug Naruto Kakashi', 'vaisselle', NULL, 'image/mug_naruto_kakashi.jpeg', 27.80, NULL),
('Mug Kunai Konoha', 'vaisselle', NULL, 'image/mug_kunai_konoha.jpg', 32.80, NULL),
('Mug Sceau Naruto', 'vaisselle', NULL, 'image/mug_sceau_naruto.jpg', 27.80, NULL),
('Boite Repas Dragon Ball Z', 'vaisselle', NULL, 'image/boite_repas_dragon_ball_z.jpg', 58.80, NULL),
('Verre Vegeta', 'vaisselle', NULL, 'image/verre_vegeta.jpg', 35.80, NULL),
('Assiette Dragon Ball Z', 'vaisselle', NULL, 'image/assiette_dragon_ball_z.jpg', 42.80, NULL),
('Assiette Son Goku', 'vaisselle', NULL, 'image/assiette_son_goku.jpg', 42.80, NULL),
('Mug Dragon Ball Z', 'vaisselle', NULL, 'image/mug_dragon_ball_z.jpg', 27.80, NULL),
('Kit Anniversaire Demon Slayer', 'vaisselle', NULL, 'image/kit_anniversaire_demon_slayer.jpg', 127.80, NULL),
('Bol Tanjiro', 'vaisselle', NULL, 'image/bol_tanjiro.png', 32.80, NULL),
('Verre Demon Slayer', 'vaisselle', NULL, 'image/verre_demon_slayer.jpg', 35.80, NULL),
('Verre Itadori Sukuna', 'vaisselle', NULL, 'image/verre_itadori_sukuna.jpg', 35.80, NULL),
('Mug Nezuko Demon', 'vaisselle', NULL, 'image/mug_nezuko_demon.jpg', 27.80, NULL),
('Mug Tanjiro Zenitsu', 'vaisselle', NULL, 'image/mug_tanjiro_zenitsu.jpg', 27.80, NULL),
('Mug Mitsuri Kanroji', 'vaisselle', NULL, 'image/mug_mitsuri_kanroji.jpg', 27.80, NULL),
('Mug Nezuko', 'vaisselle', NULL, 'image/mug_nezuko.jpg', 27.80, NULL),
('Mug Tanjiro', 'vaisselle', NULL, 'image/mug_tanjiro.jpg', 27.80, NULL),
('Mug Tomyoka', 'vaisselle', NULL, 'image/mug_tomyoka.jpg', 27.80, NULL),
('Bol Pokemon', 'vaisselle', NULL, 'image/bol_pokemon.jpg', 32.80, NULL),
('Mug Pikachu', 'vaisselle', NULL, 'image/mug_pikachu.jpg', 27.80, NULL),
('Bol Death Note', 'vaisselle', NULL, 'image/bol_death_note.jpg', 32.80, NULL),
('Mug L', 'vaisselle', NULL, 'image/mug_l.jpg', 27.80, NULL),
('Verre Tokyo Ghoul', 'vaisselle', NULL, 'image/verre_tokyo_ghoul.jpg', 35.80, NULL),
('Mug Tokyo Ghoul', 'vaisselle', NULL, 'image/mug_tokyo_ghoul.jpg', 27.80, NULL),
('Tasse et Bol My Hero Academia', 'vaisselle', NULL, 'image/tasse_et_bol_my_hero_academia.jpg', 45.80, NULL),
('Mug Saitama', 'vaisselle', NULL, 'image/mug_saitama.jpg', 27.80, NULL),
('Mug Dandadan', 'vaisselle', NULL, 'image/mug_dandadan.jpg', 27.80, NULL),
('Mug Assasination Classroom', 'vaisselle', NULL, 'image/mug_assasination_classroom.jpg', 27.80, NULL),
('Mug Spy Family', 'vaisselle', NULL, 'image/mug_spy_family.jpg', 27.80, NULL),
('Mug Sailor Moon', 'vaisselle', NULL, 'image/mug_sailor_moon.jpg', 27.80, NULL),
('Veste Luffy', 'textile', NULL, 'image/veste_luffy.jpg', 147.90, NULL),
('Veste One Piece', 'textile', NULL, 'image/veste_one_piece.jpg', 147.90, NULL),
('Jogging One Piece', 'textile', NULL, 'image/jogging_one_piece.jpg', 228.50, NULL),
('Sweat Ace', 'textile', NULL, 'image/sweat_ace.jpg', 87.80, NULL),
('Sweat Luffy Gear 5', 'textile', NULL, 'image/sweat_luffy_gear_5.jpg', 77.80, NULL),
('Sweat One Piece', 'textile', NULL, 'image/sweat_one_piece.jpg', 77.80, NULL),
('Tee Shirt Luffy', 'textile', NULL, 'image/tee_shirt_luffy.jpg', 48.00, NULL),
('Pyjama Luffy', 'textile', NULL, 'image/pyjama_luffy.jpg', 78.00, NULL),
('Tenue Luffy', 'textile', NULL, 'image/tenue_luffy.jpg', 47.50, NULL),
('Costume Luffy', 'textile', NULL, 'image/costume_luffy.jpg', 67.90, NULL),
('Costume Nami', 'textile', NULL, 'image/costume_nami.jpg', 67.90, NULL),
('Costume Sanji', 'textile', NULL, 'image/costume_sanji.jpg', 67.90, NULL),
('Costume Trafalgar Law', 'textile', NULL, 'image/costume_trafalgar_law.jpg', 97.80, NULL),
('Parure Luffy Gear 5', 'textile', NULL, 'image/parure_luffy_gear_5.jpg', 258.00, NULL),
('Parure Zoro', 'textile', NULL, 'image/parure_zoro.jpg', 248.00, NULL),
('Parure One Piece', 'textile', NULL, 'image/parure_one_piece.jpg', 238.00, NULL),
('Doudoune Akatsuki', 'textile', NULL, 'image/doudoune_akatsuki.jpg', 78.50, NULL),
('Jogging Naruto', 'textile', NULL, 'image/jogging_naruto.jpg', 158.50, NULL),
('Sweat Naruto', 'textile', NULL, 'image/sweat_naruto.jpg', 68.50, NULL),
('Tee Shirt Sasuke', 'textile', NULL, 'image/tee_shirt_sasuke.jpg', 48.50, NULL),
('Pyjama Kurama', 'textile', NULL, 'image/pyjama_kurama.jpg', 58.50, NULL),
('Costume Naruto', 'textile', NULL, 'image/costume_naruto.jpg', 55.50, NULL),
('Costume Itachi', 'textile', NULL, 'image/costume_itachi.jpg', 55.50, NULL),
('Parure Naruto', 'textile', NULL, 'image/parure_naruto.jpg', 258.50, NULL),
('Parure Akatsuki', 'textile', NULL, 'image/parure_akatsuki.jpg', 278.50, NULL),
('Parure Sasuke', 'textile', NULL, 'image/parure_sasuke.jpg', 258.50, NULL),
('Veste Black Goku', 'textile', NULL, 'image/veste_black_goku.jpg', 77.90, NULL),
('Jogging Dragon Ball Z', 'textile', NULL, 'image/jogging_dragon_ball_z.jpg', 127.90, NULL),
('Sweat San Goku Ultra Instinct', 'textile', NULL, 'image/sweat_san_goku_ultra_instinct.jpg', 68.50, NULL),
('Tee Shirt Gogeta SSB', 'textile', NULL, 'image/tee_shirt_gogeta_ssb.jpg', 47.90, NULL),
('Pyjama San Goku', 'textile', NULL, 'image/pyjama_san_goku.jpg', 55.90, NULL),
('Costume San Goku', 'textile', NULL, 'image/costume_san_goku.jpg', 50.50, NULL),
('Costume Videl', 'textile', NULL, 'image/costume_videl.jpg', 52.80, NULL),
('Parure San Goku Ultra Instinct', 'textile', NULL, 'image/parure_san_goku_ultra_instinct.jpg', 248.50, NULL),
('Parure Black Goku', 'textile', NULL, 'image/parure_black_goku.jpg', 238.50, NULL),
('Parure San Goku SS4 Vegeta SS4', 'textile', NULL, 'image/parure_san_goku_ss4_vegeta_ss4.jpg', 258.50, NULL),
('Veste Zenitsu', 'textile', NULL, 'image/veste_zenitsu.jpg', 75.50, NULL),
('Jogging Nezuko', 'textile', NULL, 'image/jogging_nezuko.jpg', 158.50, NULL),
('Sweat Tanjiro', 'textile', NULL, 'image/sweat_tanjiro.jpg', 65.50, NULL),
('Tee Shirt Inosuke', 'textile', NULL, 'image/tee_shirt_inosuke.jpg', 48.50, NULL),
('Pyjama Zenitsu', 'textile', NULL, 'image/pyjama_zenitsu.jpg', 55.50, NULL),
('Costume Zenitsu', 'textile', NULL, 'image/costume_zenitsu.jpg', 50.50, NULL),
('Costume Nezuko', 'textile', NULL, 'image/costume_nezuko.jpg', 60.50, NULL),
('Parure Demon Slayer', 'textile', NULL, 'image/parure_demon_slayer.jpg', 258.50, NULL),
('Parure Tanjiro Nezuko', 'textile', NULL, 'image/parure_tanjiro_nezuko.jpg', 268.50, NULL),
('Parure Nezuko', 'textile', NULL, 'image/parure_nezuko.jpg', 278.50, NULL),
('Veste One Punch Man', 'textile', NULL, 'image/veste_one_punch_man.jpg', 75.50, NULL),
('Jogging Saitama', 'textile', NULL, 'image/jogging_saitama.jpg', 158.50, NULL),
('Sweat Genos', 'textile', NULL, 'image/sweat_genos.jpg', 65.50, NULL),
('Tee Shirt Garou', 'textile', NULL, 'image/tee_shirt_garou.jpg', 48.50, NULL),
('Pyjama Saitama', 'textile', NULL, 'image/pyjama_saitama.jpg', 55.50, NULL),
('Costume Saitama', 'textile', NULL, 'image/costume_saitama.jpg', 50.50, NULL),
('Costume Tatsumaki', 'textile', NULL, 'image/costume_tatsumaki.jpg', 60.50, NULL),
('Parure One Punch Man', 'textile', NULL, 'image/parure_one_punch_man.jpg', 258.50, NULL),
('Parure Saitama', 'textile', NULL, 'image/parure_saitama.jpg', 268.50, NULL),
('Parure Genos', 'textile', NULL, 'image/parure_genos.jpg', 278.50, NULL),
('Body luffy', 'textile', NULL, 'image/body_luffy.jpg', 57.99, NULL),
('Bonnet naruto', 'textile', NULL, 'image/bonnet_naruto.jpeg', 57.99, NULL),
('Set 8 serviettes dbz', 'textile', NULL, 'image/set_8_serviettes_dbz.jpg', 57.99, NULL),
('T shirt gohan ss2', 'textile', NULL, 'image/t_shirt_gohan_ss2.jpg', 57.99, NULL),
('Veste akatsuki', 'textile', NULL, 'image/veste_akatsuki.jpeg', 57.99, NULL),
('Veste shenron', 'textile', NULL, 'image/veste_shenron.jpg', 57.99, NULL),
('Veste Solo Leveling', 'textile', NULL, 'image/veste_solo_leveling.jpg', 75.50, NULL),
('Jogging Solo Leveling', 'textile', NULL, 'image/jogging_solo_leveling.jpg', 158.50, NULL),
('Sweat Sung Jin Hoo', 'textile', NULL, 'image/sweat_sung_jin_hoo.jpg', 65.50, NULL),
('Tee Shirt Sung Jin Hoo', 'textile', NULL, 'image/tee_shirt_sung_jin_hoo.jpg', 48.50, NULL),
('Pyjama Solo Leveling', 'textile', NULL, 'image/pyjama_solo_leveling.jpg', 55.50, NULL),
('Costume Sung Jin Hoo', 'textile', NULL, 'image/costume_sung_jin_hoo.jpg', 50.50, NULL),
('Costume Cha Hae In', 'textile', NULL, 'image/costume_cha_hae_in.jpg', 60.50, NULL),
('Parure Sung Jin Hoo', 'textile', NULL, 'image/parure_sung_jin_hoo.jpg', 258.50, NULL),
('Parure Solo Leveling', 'textile', NULL, 'image/parure_solo_leveling.jpg', 268.50, NULL),
('Parure Sung Jin Hoo Black', 'textile', NULL, 'image/parure_sung_jin_hoo_black.jpg', 278.50, NULL);

-- Descriptions generiques propres, sans donnees personnelles.
INSERT INTO detail_articles_public (article_id, description)
SELECT id, 'Decouvrez ' || name || ' dans le catalogue MangaBook. Un article selectionne pour les passionnes de mangas, figurines et goodies.' FROM articles;
